files:
  - source: /*.csv
    translation: /translations/%language%/%original_file_name%
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,context,source_phrase,no,uk'
